class Config:
    ROUTES_MAX_QUANTITY: int = 20
    ROUTES_MIN_QUANTITY: int = 5

    TRAIN_PER_ROUTE_MIN_QUANTITY: int = 5
    TRAIN_PER_ROUTE_MAX_QUANTITY: int = 10

    CARRIAGE_MIN_QUANTITY: int = 5
    CARRIAGE_MAX_QUANTITY: int = 20
